name: Deploy to Skynet

on:
  push:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Deploy to Skynet'
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: './'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
          skynet-jwt: ${{ secrets.SKYNETPRO_JWT}}
          portal-url: https://skynetpro.net
